# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  galyonj.com:
    site_hosts:
      - canonical: galyonj.com
        redirects:
          - www.galyonj.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:galyonj/crown-of-horns.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: true
      subdomains: false
      domain_current_site: galyonj.com
    ssl:
      enabled: true
      provider: self-signed
    cache:
      enabled: true
